/-
Copyright (c) 2026 kiyo-e. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: kiyo-e
-/
import CrooksJarzynski.ContinuousTimeJumpConcat
import CrooksJarzynski.ContinuousTimeJumpDrivenConcat
import CrooksJarzynski.ContinuousTimeJumpDrivenPhysical
import CrooksJarzynski.ContinuousTimeJumpDrivenWorkDistribution
import CrooksJarzynski.ContinuousTimeJumpDrivenThreeStateTwoWindow
import CrooksJarzynski.ContinuousTimeJumpDrivenTwoStateComparison
import CrooksJarzynski.MeasureProtocolMarkedEndpoints
import CrooksJarzynski.ContinuousTimeJumpDrivenEndpointLaw
import CrooksJarzynski.ContinuousTimeJumpDrivenEndpointExp
import CrooksJarzynski.ContinuousTimeJumpDrivenGlobalCrooks

/-!
# Axiom audit for stepwise driven jump protocols

This module keeps the driven-protocol audit separate from the historical
headline list while subjecting both files to the same CI allowlist.
-/

#print axioms CrooksJarzynski.MeasureProtocol.ContinuousTimeJump.JumpPath.trajectory_concat_left
#print axioms CrooksJarzynski.MeasureProtocol.ContinuousTimeJump.JumpPath.trajectory_concat_right
#print axioms CrooksJarzynski.MeasureProtocol.ContinuousTimeJump.JumpPath.isValid_concat
#print axioms CrooksJarzynski.MeasureProtocol.ContinuousTimeJump.JumpPath.totalHoldingTime_concat
#print axioms CrooksJarzynski.MeasureProtocol.ContinuousTimeJump.FullPath.measurable_concat
#print axioms CrooksJarzynski.MeasureProtocol.ContinuousTimeJump.FullPath.trajectory_concat_left
#print axioms CrooksJarzynski.MeasureProtocol.ContinuousTimeJump.FullPath.trajectory_concat_right
#print axioms CrooksJarzynski.MeasureProtocol.ContinuousTimeJump.Driven.isValid_concatenateWindows
#print axioms CrooksJarzynski.MeasureProtocol.ContinuousTimeJump.Driven.totalHoldingTime_concatenateWindows
#print axioms CrooksJarzynski.MeasureProtocol.ContinuousTimeJump.Driven.work_eq_sum
#print axioms CrooksJarzynski.MeasureProtocol.ContinuousTimeJump.Driven.work_two_eq
#print axioms CrooksJarzynski.MeasureProtocol.ContinuousTimeJump.Driven.reverseDrivenLaw_two_eq
#print axioms CrooksJarzynski.MeasureProtocol.ContinuousTimeJump.Driven.norm_work_le
#print axioms CrooksJarzynski.MeasureProtocol.ContinuousTimeJump.Driven.integrable_work_of_isFiniteMeasure
#print axioms CrooksJarzynski.MeasureProtocol.ContinuousTimeJump.Driven.integrable_work
#print axioms CrooksJarzynski.MeasureProtocol.ContinuousTimeJump.Driven.integrable_work_reverse
#print axioms CrooksJarzynski.MeasureProtocol.ContinuousTimeJump.FiniteJumpGenerator.isProbabilityMeasure_gibbsPathLaw
#print axioms CrooksJarzynski.MeasureProtocol.ContinuousTimeJump.Driven.forwardDrivenLaw_ae_isBoundaryConsistent
#print axioms CrooksJarzynski.MeasureProtocol.ContinuousTimeJump.Driven.reverseDrivenLaw_ae_isBoundaryConsistent
#print axioms CrooksJarzynski.MeasureProtocol.ContinuousTimeJump.Driven.forwardDrivenLaw_ae_isProtocolValid
#print axioms CrooksJarzynski.MeasureProtocol.ContinuousTimeJump.Driven.reverseDrivenLaw_ae_isProtocolValid
#print axioms CrooksJarzynski.MeasureProtocol.ContinuousTimeJump.FiniteJumpGenerator.windowBalance_of_gibbsDetailedBalance
#print axioms CrooksJarzynski.MeasureProtocol.ContinuousTimeJump.Driven.crooks_of_gibbsDetailedBalance
#print axioms CrooksJarzynski.MeasureProtocol.ContinuousTimeJump.Driven.jarzynski_of_gibbsDetailedBalance
#print axioms CrooksJarzynski.MeasureProtocol.ContinuousTimeJump.Driven.second_law_of_gibbsDetailedBalance
#print axioms CrooksJarzynski.MeasureProtocol.ContinuousTimeJump.Driven.reverseWork_eq_neg
#print axioms CrooksJarzynski.MeasureProtocol.ContinuousTimeJump.Driven.work_distribution_crooks_of_gibbsDetailedBalance
#print axioms CrooksJarzynski.MeasureProtocol.ContinuousTimeJump.Driven.work_distribution_crooks_reverseWork_of_gibbsDetailedBalance
#print axioms CrooksJarzynski.MeasureProtocol.ContinuousTimeJump.Driven.crooks_work_atom_of_gibbsDetailedBalance
#print axioms CrooksJarzynski.MeasureProtocol.ContinuousTimeJump.Driven.ThreeStateTwoWindow.generator_isGibbsDetailedBalance
#print axioms CrooksJarzynski.MeasureProtocol.ContinuousTimeJump.Driven.ThreeStateTwoWindow.crooks
#print axioms CrooksJarzynski.MeasureProtocol.ContinuousTimeJump.Driven.ThreeStateTwoWindow.jarzynski_eq_one
#print axioms CrooksJarzynski.MeasureProtocol.ContinuousTimeJump.Driven.ThreeStateTwoWindow.second_law
#print axioms CrooksJarzynski.MeasureProtocol.ContinuousTimeJump.Driven.ThreeStateTwoWindow.work_not_constant
#print axioms CrooksJarzynski.MeasureProtocol.ContinuousTimeJump.Driven.ThreeStateTwoWindow.work_zero_atom_pos
#print axioms CrooksJarzynski.MeasureProtocol.ContinuousTimeJump.Driven.ThreeStateTwoWindow.work_log_two_atom_pos
#print axioms CrooksJarzynski.MeasureProtocol.ContinuousTimeJump.TwoState.AsymmetricExample.physicalFiniteGenerator_generator_eq
#print axioms CrooksJarzynski.MeasureProtocol.ContinuousTimeJump.TwoState.AsymmetricExample.physicalFiniteGenerator_isGibbsDetailedBalance
#print axioms CrooksJarzynski.MeasureProtocol.ContinuousTimeJump.TwoState.AsymmetricExample.connectedDrivenWork_oneWindow_eq_thermodynamicWork
#print axioms CrooksJarzynski.MeasureProtocol.ContinuousTimeJump.TwoState.AsymmetricExample.forwardWindowKernel_ae_thermodynamicWork
#print axioms CrooksJarzynski.MeasureProtocol.ContinuousTimeJump.TwoState.AsymmetricExample.driven_oneWindow_crooks_physical
#print axioms CrooksJarzynski.MeasureProtocol.ContinuousTimeJump.TwoState.AsymmetricExample.driven_oneWindow_jarzynski_physical
#print axioms CrooksJarzynski.MeasureProtocol.ContinuousTimeJump.TwoState.AsymmetricExample.integrable_drivenOneWindowWork
#print axioms CrooksJarzynski.MeasureProtocol.ContinuousTimeJump.TwoState.AsymmetricExample.driven_oneWindow_second_law
#print axioms CrooksJarzynski.MeasureProtocol.ContinuousTimeJump.TwoState.AsymmetricExample.physicalFiniteGenerator_terminalState_real_singleton_eq_legacy
#print axioms CrooksJarzynski.MeasureProtocol.ContinuousTimeJump.TwoState.AsymmetricExample.map_physicalFiniteGenerator_pathLawFrom_terminalState_eq_legacy
#print axioms CrooksJarzynski.MeasureProtocol.Marked.map_reversedForwardPathMeasure_eraseMarks
#print axioms CrooksJarzynski.MeasureProtocol.ContinuousTimeJump.FiniteJumpGenerator.endpointMarginal_forwardWindowKernel
#print axioms CrooksJarzynski.MeasureProtocol.ContinuousTimeJump.Driven.map_forwardDrivenLaw_endpoints
#print axioms CrooksJarzynski.MeasureProtocol.ContinuousTimeJump.Driven.forwardDrivenLaw_endpointCylinder_eq_exp_product
#print axioms CrooksJarzynski.MeasureProtocol.ContinuousTimeJump.Driven.ThreeStateTwoWindow.work_zero_same_endpoints_event_pos
#print axioms CrooksJarzynski.MeasureProtocol.ContinuousTimeJump.Driven.ThreeStateTwoWindow.work_log_two_same_endpoints_event_pos
#print axioms CrooksJarzynski.MeasureProtocol.ContinuousTimeJump.Driven.ThreeStateTwoWindow.work_not_ae_initialFinalFunction
#print axioms CrooksJarzynski.MeasureProtocol.ContinuousTimeJump.Driven.ThreeStateTwoWindow.work_not_ae_finalStateFunction
#print axioms CrooksJarzynski.MeasureProtocol.ContinuousTimeJump.JumpPath.trajectory_zero_of_not_hasJumpAt_zero
#print axioms CrooksJarzynski.MeasureProtocol.ContinuousTimeJump.JumpPath.not_hasJumpAt_zero_of_isValid
#print axioms CrooksJarzynski.MeasureProtocol.ContinuousTimeJump.FullPath.trajectory_zero_of_not_hasJumpAt_zero
#print axioms CrooksJarzynski.MeasureProtocol.ContinuousTimeJump.FullPath.not_hasJumpAt_zero_of_isValid
#print axioms CrooksJarzynski.MeasureProtocol.ContinuousTimeJump.FullPath.trajectory_total_eq_terminal
#print axioms CrooksJarzynski.MeasureProtocol.ContinuousTimeJump.FullPath.measurable_concat_prod
#print axioms CrooksJarzynski.MeasureProtocol.ContinuousTimeJump.Driven.measurable_concatenateWindows
#print axioms CrooksJarzynski.MeasureProtocol.ContinuousTimeJump.Driven.boundaryTime_zero
#print axioms CrooksJarzynski.MeasureProtocol.ContinuousTimeJump.Driven.boundaryTime_last
#print axioms CrooksJarzynski.MeasureProtocol.ContinuousTimeJump.Driven.boundaryTime_succ
#print axioms CrooksJarzynski.MeasureProtocol.ContinuousTimeJump.Driven.measurable_globalWork
#print axioms CrooksJarzynski.MeasureProtocol.ContinuousTimeJump.Driven.measurable_globalReverseWork
#print axioms CrooksJarzynski.MeasureProtocol.ContinuousTimeJump.Driven.terminalState_concatenateWindows
#print axioms CrooksJarzynski.MeasureProtocol.ContinuousTimeJump.Driven.forwardDrivenLaw_ae_windowRegular
#print axioms CrooksJarzynski.MeasureProtocol.ContinuousTimeJump.Driven.reverseDrivenLaw_ae_windowRegular
#print axioms CrooksJarzynski.MeasureProtocol.ContinuousTimeJump.Driven.trajectory_concatenateWindows_boundary_ae
#print axioms CrooksJarzynski.MeasureProtocol.ContinuousTimeJump.Driven.trajectory_concatenateWindows_boundary_ae_reverse
#print axioms CrooksJarzynski.MeasureProtocol.ContinuousTimeJump.Driven.work_comp_concatenateWindows_ae
#print axioms CrooksJarzynski.MeasureProtocol.ContinuousTimeJump.Driven.work_comp_concatenateWindows_ae_reverse
#print axioms CrooksJarzynski.MeasureProtocol.ContinuousTimeJump.Driven.map_globalWork_forwardGlobalLaw
#print axioms CrooksJarzynski.MeasureProtocol.ContinuousTimeJump.Driven.map_globalWork_reverseGlobalLaw
#print axioms CrooksJarzynski.MeasureProtocol.ContinuousTimeJump.Driven.map_globalReverseWork_reverseGlobalLaw
#print axioms CrooksJarzynski.MeasureProtocol.ContinuousTimeJump.Driven.integrable_globalWork
#print axioms CrooksJarzynski.MeasureProtocol.ContinuousTimeJump.Driven.integrable_globalWork_reverse
#print axioms CrooksJarzynski.MeasureProtocol.ContinuousTimeJump.Driven.forwardGlobalLaw_ae_isValid
#print axioms CrooksJarzynski.MeasureProtocol.ContinuousTimeJump.Driven.forwardGlobalLaw_ae_totalHoldingTime
#print axioms CrooksJarzynski.MeasureProtocol.ContinuousTimeJump.Driven.reverseGlobalLaw_ae_isValid
#print axioms CrooksJarzynski.MeasureProtocol.ContinuousTimeJump.Driven.reverseGlobalLaw_ae_totalHoldingTime
#print axioms CrooksJarzynski.MeasureProtocol.ContinuousTimeJump.Driven.global_work_distribution_crooks_of_gibbsDetailedBalance
#print axioms CrooksJarzynski.MeasureProtocol.ContinuousTimeJump.Driven.global_work_distribution_crooks_reverseWork_of_gibbsDetailedBalance
#print axioms CrooksJarzynski.MeasureProtocol.ContinuousTimeJump.Driven.global_crooks_work_atom_of_gibbsDetailedBalance
#print axioms CrooksJarzynski.MeasureProtocol.ContinuousTimeJump.Driven.global_crooks_of_gibbsDetailedBalance
#print axioms CrooksJarzynski.MeasureProtocol.ContinuousTimeJump.Driven.global_jarzynski_of_gibbsDetailedBalance
#print axioms CrooksJarzynski.MeasureProtocol.ContinuousTimeJump.Driven.global_second_law_of_gibbsDetailedBalance
#print axioms CrooksJarzynski.MeasureProtocol.ContinuousTimeJump.Driven.ThreeStateTwoWindow.global_work_zero_atom_pos
#print axioms CrooksJarzynski.MeasureProtocol.ContinuousTimeJump.Driven.ThreeStateTwoWindow.global_work_log_two_atom_pos
