import CrooksJarzynski.TimeReversal
import Mathlib.Analysis.SpecificLimits.Basic

/-!
# Continuous-time limit of discrete work conventions

This module separates the two standard discrete work conventions from the
probability structure of a protocol.  It proves a discrete summation-by-parts
identity for their difference, a path-independent finite-difference bound, and
an `O(1/N)` uniform-mesh estimate.  The estimate implies that the two
conventions converge to one another for every sequence of paths.

The result concerns the finite-variation work generated by changing the energy
schedule in time.  It is not an Itô--Stratonovich conversion theorem.
-/

open Filter
open scoped BigOperators Topology

namespace CrooksJarzynski

universe u

namespace WorkConvention

variable {Ω : Type u}

/-- Energy change across edge `t`, evaluated at a fixed state. -/
def increment {n : ℕ} (E : Fin (n + 1) → Ω → ℝ) (t : Fin n) (x : Ω) : ℝ :=
  E t.succ x - E t.castSucc x

/-- Work obtained by evaluating each energy change at the state before the transition. -/
noncomputable def quenchThenTransitionWork {n : ℕ}
    (E : Fin (n + 1) → Ω → ℝ) (x : Fin (n + 1) → Ω) : ℝ :=
  ∑ t : Fin n, increment E t (x t.castSucc)

/-- Work obtained by evaluating each energy change at the state after the transition. -/
noncomputable def transitionThenQuenchWork {n : ℕ}
    (E : Fin (n + 1) → Ω → ℝ) (x : Fin (n + 1) → Ω) : ℝ :=
  ∑ t : Fin n, increment E t (x t.succ)

/-- The exact difference between the two conventions, before summation by parts. -/
theorem difference {n : ℕ} (E : Fin (n + 1) → Ω → ℝ) (x : Fin (n + 1) → Ω) :
    transitionThenQuenchWork E x - quenchThenTransitionWork E x =
      ∑ t : Fin n, (increment E t (x t.succ) - increment E t (x t.castSucc)) := by
  unfold transitionThenQuenchWork quenchThenTransitionWork
  rw [Finset.sum_sub_distrib]

/-- Discrete summation by parts for the transport of a time-dependent observable
along an arbitrary path.  No regularity of the path is required. -/
theorem sum_transport_summationByParts {n : ℕ}
    (q : Fin (n + 1) → Ω → ℝ) (x : Fin (n + 2) → Ω) :
    (∑ t : Fin (n + 1), (q t (x t.succ) - q t (x t.castSucc))) =
      q (Fin.last n) (x (Fin.last (n + 1))) - q 0 (x 0) +
        ∑ t : Fin n,
          (q t.castSucc (x t.castSucc.succ) -
            q t.succ (x t.castSucc.succ)) := by
  calc
    (∑ t : Fin (n + 1), (q t (x t.succ) - q t (x t.castSucc))) =
        (∑ t : Fin (n + 1), q t (x t.succ)) -
          ∑ t : Fin (n + 1), q t (x t.castSucc) := by
            rw [Finset.sum_sub_distrib]
    _ = ((∑ t : Fin n, q t.castSucc (x t.castSucc.succ)) +
          q (Fin.last n) (x (Fin.last n).succ)) -
        (q 0 (x (0 : Fin (n + 1)).castSucc) +
          ∑ t : Fin n, q t.succ (x t.succ.castSucc)) := by
            rw [Fin.sum_univ_castSucc, Fin.sum_univ_succ]
    _ = q (Fin.last n) (x (Fin.last (n + 1))) - q 0 (x 0) +
        ∑ t : Fin n,
          (q t.castSucc (x t.castSucc.succ) -
            q t.succ (x t.castSucc.succ)) := by
      have hlast : (Fin.last n).succ = Fin.last (n + 1) := by
        apply Fin.ext
        rfl
      have hzero : (0 : Fin (n + 1)).castSucc = (0 : Fin (n + 2)) := rfl
      have hindex (t : Fin n) : t.succ.castSucc = t.castSucc.succ := by
        apply Fin.ext
        rfl
      rw [hlast, hzero]
      simp_rw [hindex]
      rw [Finset.sum_sub_distrib]
      ring

/-- Summation by parts for the difference of the two work conventions. -/
theorem difference_summationByParts {n : ℕ}
    (E : Fin (n + 2) → Ω → ℝ) (x : Fin (n + 2) → Ω) :
    transitionThenQuenchWork E x - quenchThenTransitionWork E x =
      increment E (Fin.last n) (x (Fin.last (n + 1))) - increment E 0 (x 0) +
        ∑ t : Fin n,
          (increment E t.castSucc (x t.castSucc.succ) -
            increment E t.succ (x t.castSucc.succ)) := by
  rw [difference]
  exact sum_transport_summationByParts (q := increment E) x

/-- A path-independent estimate following from the summation-by-parts identity. -/
theorem abs_sum_transport_le {n : ℕ}
    (q : Fin (n + 1) → Ω → ℝ) (x : Fin (n + 2) → Ω) {A B : ℝ}
    (hq : ∀ t z, |q t z| ≤ A)
    (hvariation : ∀ (t : Fin n) z, |q t.castSucc z - q t.succ z| ≤ B) :
    |∑ t : Fin (n + 1), (q t (x t.succ) - q t (x t.castSucc))| ≤
      2 * A + (n : ℝ) * B := by
  rw [sum_transport_summationByParts]
  have hsum :
      (∑ t : Fin n,
          |q t.castSucc (x t.castSucc.succ) - q t.succ (x t.castSucc.succ)|) ≤
        ∑ _ : Fin n, B := by
    apply Finset.sum_le_sum
    intro t _
    exact hvariation t (x t.castSucc.succ)
  have hcard : (∑ _ : Fin n, B) = (n : ℝ) * B := by
    simp
  calc
    |q (Fin.last n) (x (Fin.last (n + 1))) - q 0 (x 0) +
        ∑ t : Fin n,
          (q t.castSucc (x t.castSucc.succ) -
            q t.succ (x t.castSucc.succ))| ≤
        |q (Fin.last n) (x (Fin.last (n + 1))) - q 0 (x 0)| +
          |∑ t : Fin n,
            (q t.castSucc (x t.castSucc.succ) -
              q t.succ (x t.castSucc.succ))| := abs_add _ _
    _ ≤ (|q (Fin.last n) (x (Fin.last (n + 1)))| + |q 0 (x 0)|) +
          ∑ t : Fin n,
            |q t.castSucc (x t.castSucc.succ) -
              q t.succ (x t.castSucc.succ)| := by
      apply add_le_add
      · exact abs_sub _ _
      · exact Finset.abs_sum_le_sum_abs _ _
    _ ≤ (A + A) + ∑ _ : Fin n, B := by
      apply add_le_add
      · exact add_le_add
          (hq (Fin.last n) (x (Fin.last (n + 1))))
          (hq 0 (x 0))
      · exact hsum
    _ = 2 * A + (n : ℝ) * B := by
      rw [hcard]
      ring

/-- Finite-difference estimate for the discrepancy of the work conventions. -/
theorem abs_difference_le {n : ℕ}
    (E : Fin (n + 2) → Ω → ℝ) (x : Fin (n + 2) → Ω) {A B : ℝ}
    (hincrement : ∀ t z, |increment E t z| ≤ A)
    (hvariation : ∀ (t : Fin n) z,
      |increment E t.castSucc z - increment E t.succ z| ≤ B) :
    |transitionThenQuenchWork E x - quenchThenTransitionWork E x| ≤
      2 * A + (n : ℝ) * B := by
  rw [difference]
  exact abs_sum_transport_le (q := increment E) x hincrement hvariation

/-- If first time differences are `O(h)` and adjacent first differences vary by
`O(h²)`, then the discrepancy is bounded by `2 M h + n L h²`. -/
theorem abs_difference_le_finiteDifferences {n : ℕ}
    (E : Fin (n + 2) → Ω → ℝ) (x : Fin (n + 2) → Ω)
    {M L h : ℝ}
    (hincrement : ∀ t z, |increment E t z| ≤ M * h)
    (hvariation : ∀ (t : Fin n) z,
      |increment E t.castSucc z - increment E t.succ z| ≤ L * h ^ 2) :
    |transitionThenQuenchWork E x - quenchThenTransitionWork E x| ≤
      2 * (M * h) + (n : ℝ) * (L * h ^ 2) :=
  abs_difference_le E x hincrement hvariation

/-- A mesh-size form of the finite-difference estimate. -/
theorem abs_difference_le_mesh {n : ℕ}
    (E : Fin (n + 2) → Ω → ℝ) (x : Fin (n + 2) → Ω)
    {M L h T : ℝ} (hL : 0 ≤ L) (hh : 0 ≤ h)
    (hmesh : (n : ℝ) * h ≤ T)
    (hincrement : ∀ t z, |increment E t z| ≤ M * h)
    (hvariation : ∀ (t : Fin n) z,
      |increment E t.castSucc z - increment E t.succ z| ≤ L * h ^ 2) :
    |transitionThenQuenchWork E x - quenchThenTransitionWork E x| ≤
      (2 * M + L * T) * h := by
  have hlast : (n : ℝ) * (L * h ^ 2) ≤ L * T * h := by
    calc
      (n : ℝ) * (L * h ^ 2) = (L * h) * ((n : ℝ) * h) := by ring
      _ ≤ (L * h) * T :=
        mul_le_mul_of_nonneg_left hmesh (mul_nonneg hL hh)
      _ = L * T * h := by ring
  calc
    |transitionThenQuenchWork E x - quenchThenTransitionWork E x| ≤
        2 * (M * h) + (n : ℝ) * (L * h ^ 2) :=
      abs_difference_le_finiteDifferences E x hincrement hvariation
    _ ≤ 2 * (M * h) + L * T * h := add_le_add_left hlast _
    _ = (2 * M + L * T) * h := by ring

/-- On a uniform partition of `[0,T]` into `n+1` steps, the two conventions
differ by at most `T (2M + LT)/(n+1)`, uniformly over all paths. -/
theorem uniformMesh_difference_bound {n : ℕ}
    (E : Fin (n + 2) → Ω → ℝ) (x : Fin (n + 2) → Ω)
    {M L T : ℝ} (hT : 0 ≤ T) (hL : 0 ≤ L)
    (hincrement : ∀ t z,
      |increment E t z| ≤ M * (T / ((n : ℝ) + 1)))
    (hvariation : ∀ (t : Fin n) z,
      |increment E t.castSucc z - increment E t.succ z| ≤
        L * (T / ((n : ℝ) + 1)) ^ 2) :
    |transitionThenQuenchWork E x - quenchThenTransitionWork E x| ≤
      (2 * M + L * T) * (T / ((n : ℝ) + 1)) := by
  have hden : 0 < (n : ℝ) + 1 := by positivity
  have hh : 0 ≤ T / ((n : ℝ) + 1) := div_nonneg hT hden.le
  have hn : (n : ℝ) ≤ (n : ℝ) + 1 := by linarith
  have hmesh : (n : ℝ) * (T / ((n : ℝ) + 1)) ≤ T := by
    have hfrac : (n : ℝ) / ((n : ℝ) + 1) ≤ 1 := (div_le_one hden).2 hn
    calc
      (n : ℝ) * (T / ((n : ℝ) + 1)) =
          T * ((n : ℝ) / ((n : ℝ) + 1)) := by ring
      _ ≤ T * 1 := mul_le_mul_of_nonneg_left hfrac hT
      _ = T := by ring
  exact abs_difference_le_mesh E x hL hh hmesh hincrement hvariation

/-- The path-independent uniform-mesh estimate implies convergence of the two
work conventions for every sequence of paths. -/
theorem uniformMesh_difference_tendsto_zero
    (E : (n : ℕ) → Fin (n + 2) → Ω → ℝ)
    (x : (n : ℕ) → Fin (n + 2) → Ω)
    {M L T : ℝ} (hT : 0 ≤ T) (hL : 0 ≤ L)
    (hincrement : ∀ n t z,
      |increment (E n) t z| ≤ M * (T / ((n : ℝ) + 1)))
    (hvariation : ∀ n (t : Fin n) z,
      |increment (E n) t.castSucc z - increment (E n) t.succ z| ≤
        L * (T / ((n : ℝ) + 1)) ^ 2) :
    Tendsto
      (fun n => transitionThenQuenchWork (E n) (x n) -
        quenchThenTransitionWork (E n) (x n))
      atTop (𝓝 0) := by
  apply squeeze_zero_norm
  · intro n
    simpa [Real.norm_eq_abs] using
      uniformMesh_difference_bound (E := E n) (x := x n) hT hL
        (hincrement n) (hvariation n)
  · have hconst :
        Tendsto (fun _ : ℕ => (2 * M + L * T) * T) atTop
          (𝓝 ((2 * M + L * T) * T)) := tendsto_const_nhds
    have hinv :
        Tendsto (fun n : ℕ => 1 / ((n : ℝ) + 1)) atTop (𝓝 0) :=
      tendsto_one_div_add_atTop_nhds_zero_nat
    simpa [div_eq_mul_inv, mul_assoc] using hconst.mul hinv

end WorkConvention

namespace Protocol

variable {Ω : Type u} [Fintype Ω] [Nonempty Ω]
variable {n : ℕ}

/-- A protocol's energy schedule, restricted to its finite time horizon. -/
def workEnergySchedule (P : Protocol Ω n) : Fin (n + 1) → Ω → ℝ :=
  fun t => P.energy t.val

/-- The existing quench-then-transition work is the probability-free schedule work. -/
theorem work_eq_workConvention (P : Protocol Ω n) (γ : Trajectory Ω n) :
    P.work γ =
      WorkConvention.quenchThenTransitionWork P.workEnergySchedule
        (Trajectory.stateAt γ) := by
  rw [P.work_eq_sum_quenchThenTransitionIncrement γ]
  unfold WorkConvention.quenchThenTransitionWork
  apply Finset.sum_congr rfl
  intro t _
  unfold quenchThenTransitionIncrement WorkConvention.increment workEnergySchedule
  rfl

/-- The existing transition-then-quench work is the probability-free schedule work. -/
theorem transitionThenQuenchWork_eq_workConvention
    (P : Protocol Ω n) (γ : Trajectory Ω n) :
    P.transitionThenQuenchWork γ =
      WorkConvention.transitionThenQuenchWork P.workEnergySchedule
        (Trajectory.stateAt γ) := by
  unfold transitionThenQuenchWork WorkConvention.transitionThenQuenchWork
  apply Finset.sum_congr rfl
  intro t _
  unfold transitionThenQuenchIncrement WorkConvention.increment workEnergySchedule
  rfl

/-- Protocol-facing form of the uniform-mesh discrepancy estimate.  The bound
is independent of the transition kernels and of the chosen trajectory. -/
theorem workConvention_uniformMesh_bound
    (P : Protocol Ω (n + 1)) (γ : Trajectory Ω (n + 1))
    {M L T : ℝ} (hT : 0 ≤ T) (hL : 0 ≤ L)
    (hincrement : ∀ t z,
      |WorkConvention.increment P.workEnergySchedule t z| ≤
        M * (T / ((n : ℝ) + 1)))
    (hvariation : ∀ (t : Fin n) z,
      |WorkConvention.increment P.workEnergySchedule t.castSucc z -
          WorkConvention.increment P.workEnergySchedule t.succ z| ≤
        L * (T / ((n : ℝ) + 1)) ^ 2) :
    |P.transitionThenQuenchWork γ - P.work γ| ≤
      (2 * M + L * T) * (T / ((n : ℝ) + 1)) := by
  rw [P.transitionThenQuenchWork_eq_workConvention γ,
    P.work_eq_workConvention γ]
  exact WorkConvention.uniformMesh_difference_bound
    (E := P.workEnergySchedule) (x := Trajectory.stateAt γ)
    hT hL hincrement hvariation

end Protocol

end CrooksJarzynski
