/-
Copyright (c) 2026 kiyo-e. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: kiyo-e
-/
import CrooksJarzynski.ContinuousTimeJumpDrivenWindowBalance
import CrooksJarzynski.ContinuousTimeJumpDrivenConnectedPath
import CrooksJarzynski.ContinuousTimeJumpDrivenWorkSum
import CrooksJarzynski.ContinuousTimeJumpTwoStatePhysicalWork

/-!
# The asymmetric final quench as a one-window driven protocol

This module specializes the general finite-generator driven construction to the
existing asymmetric two-state chain. It identifies the generator, rates, work,
and free-energy difference, and then derives one-window Crooks, Jarzynski, and
second-law statements in the variables of the earlier final-quench example.
-/

open MeasureTheory ProbabilityTheory
open scoped ENNReal BigOperators ProbabilityTheory

namespace CrooksJarzynski
namespace MeasureProtocol
namespace ContinuousTimeJump
namespace TwoState
namespace AsymmetricExample

/-- The finite jump generator underlying the asymmetric two-state example. -/
def physicalFiniteGenerator : FiniteJumpGenerator State where
  jumpRate x y := match x, y with
    | .zero, .one => 2
    | .one, .zero => 1
    | _, _ => 0
  jumpRate_self := by
    intro x
    cases x <;> rfl

@[simp]
theorem physicalFiniteGenerator_escapeRate_zero :
    physicalFiniteGenerator.escapeRate State.zero = 2 := by
  rw [FiniteJumpGenerator.escapeRate,
    show (Finset.univ : Finset State) = {.zero, .one} by decide,
    Finset.sum_pair (by decide)]
  norm_num [physicalFiniteGenerator]

@[simp]
theorem physicalFiniteGenerator_escapeRate_one :
    physicalFiniteGenerator.escapeRate State.one = 1 := by
  rw [FiniteJumpGenerator.escapeRate,
    show (Finset.univ : Finset State) = {.zero, .one} by decide,
    Finset.sum_pair (by decide)]
  norm_num [physicalFiniteGenerator]

@[simp]
theorem physicalFiniteGenerator_pathEscapeRate
    {n : ℕ} (i : Fin (n + 1)) (x : State) :
    physicalFiniteGenerator.pathEscapeRate i x = escapeRate i x := by
  cases x <;> simp [FiniteJumpGenerator.pathEscapeRate, escapeRate]

@[simp]
theorem physicalFiniteGenerator_pathJumpRate
    {n : ℕ} (i : Fin n) (x y : State) :
    physicalFiniteGenerator.pathJumpRate i x y = jumpRate i x y := by
  cases x <;> cases y <;> rfl

/-- The conservative matrix generated by the finite-generator structure is the
physical matrix used by the earlier asymmetric example. -/
theorem physicalFiniteGenerator_generator_eq :
    physicalFiniteGenerator.generator = physicalGenerator := by
  funext x y
  cases x <;> cases y
  · simp [FiniteJumpGenerator.generator, physicalGenerator,
      physicalEscapeRate]
  · norm_num [FiniteJumpGenerator.generator, physicalGenerator,
      physicalFiniteGenerator, physicalJumpRate]
  · norm_num [FiniteJumpGenerator.generator, physicalGenerator,
      physicalFiniteGenerator, physicalJumpRate]
  · simp [FiniteJumpGenerator.generator, physicalGenerator,
      physicalEscapeRate]

/-- The explicit asymmetric generator satisfies the Gibbs detailed-balance
hypothesis used by the driven-window theorem. -/
theorem physicalFiniteGenerator_isGibbsDetailedBalance :
    physicalFiniteGenerator.IsGibbsDetailedBalance
      thermodynamicBeta initialEnergy := by
  unfold FiniteJumpGenerator.IsGibbsDetailedBalance
    FiniteJumpGenerator.IsDetailedBalanceWeight
  intro x y
  cases x <;> cases y <;>
    norm_num [physicalFiniteGenerator, thermodynamicBeta, initialEnergy,
      Real.exp_log (by norm_num : (0 : ℝ) < 2)]

/-- The two endpoint energy landscapes of the final-quench experiment. -/
noncomputable def oneWindowEnergy (i : Fin 2) : State → ℝ :=
  Fin.cases initialEnergy (fun _ => finalEnergy) i

@[simp]
theorem oneWindowEnergy_zero : oneWindowEnergy 0 = initialEnergy := by
  rfl

@[simp]
theorem oneWindowEnergy_one : oneWindowEnergy 1 = finalEnergy := by
  rfl

/-- The unique protocol window uses the asymmetric physical generator. -/
def oneWindowGenerator : Fin 1 → FiniteJumpGenerator State :=
  fun _ => physicalFiniteGenerator

/-- The unique protocol window has duration `T`. -/
def oneWindowDuration (T : NNReal) : Fin 1 → NNReal :=
  fun _ => T

/-- The unique protocol window satisfies the Gibbs detailed-balance hypothesis
required by the driven theorem. -/
theorem oneWindow_isGibbsDetailedBalance (i : Fin 1) :
    (oneWindowGenerator i).IsGibbsDetailedBalance
      thermodynamicBeta (oneWindowEnergy i.castSucc) := by
  fin_cases i
  simpa [oneWindowGenerator] using
    physicalFiniteGenerator_isGibbsDetailedBalance

/-- On the one-window carrier, the general driven work is exactly the real work
of the existing asymmetric final-quench example. -/
@[simp]
theorem drivenWork_oneWindow_eq_thermodynamicStateWork
    (γ : Driven.Path State 1) :
    Driven.work oneWindowEnergy γ = thermodynamicStateWork γ.1 := by
  rw [Driven.work_one]
  simp [thermodynamicStateWork]

/-- Whenever the stored path has the recorded terminal endpoint, the driven
one-window work agrees pointwise with the existing full-path work observable. -/
theorem drivenWork_oneWindow_eq_thermodynamicWork_of_boundary
    (γ : Driven.Path State 1)
    (hterminal : FullPath.terminalState γ.2.1.2 = γ.1) :
    Driven.work oneWindowEnergy γ = thermodynamicWork γ.2.1.2 := by
  rw [drivenWork_oneWindow_eq_thermodynamicStateWork]
  simp [thermodynamicWork, hterminal]

/-- On the structurally connected one-window carrier, the driven work and the
existing complete-path work agree without an almost-sure qualification. -/
@[simp]
theorem connectedDrivenWork_oneWindow_eq_thermodynamicWork
    (γ : Driven.ConnectedPath State 1) :
    Driven.work oneWindowEnergy γ.1 = thermodynamicWork γ.1.2.1.2 :=
  drivenWork_oneWindow_eq_thermodynamicWork_of_boundary γ.1 γ.2.2.1

/-- The endpoint work read from a forward window agrees almost surely with the
existing full-path final-quench work. -/
theorem forwardWindowKernel_ae_thermodynamicWork
    (T : NNReal) (x : State) :
    (fun p : State × FullPath State => thermodynamicStateWork p.1) =ᵐ[
      physicalFiniteGenerator.forwardWindowKernel T x]
      fun p => thermodynamicWork p.2 := by
  filter_upwards
    [physicalFiniteGenerator.forwardWindowKernel_ae_boundary T x] with p hp
  unfold thermodynamicWork
  exact congrArg thermodynamicStateWork hp.2.symm

/-- At inverse temperature one, the general finite-state free energy agrees
with the explicit free energy used by the asymmetric example. -/
theorem finiteFreeEnergy_eq_explicit (energy : State → ℝ) :
    FiniteJumpGenerator.finiteFreeEnergy thermodynamicBeta energy =
      finiteFreeEnergy energy := by
  simp [FiniteJumpGenerator.finiteFreeEnergy,
    FiniteJumpGenerator.finitePartitionFunction,
    finiteFreeEnergy, finitePartitionFunction, thermodynamicBeta]

/-- The general driven free-energy difference specializes to the explicit
asymmetric final-quench free-energy difference. -/
@[simp]
theorem drivenDeltaFreeEnergy_oneWindow_eq :
    Driven.deltaFreeEnergy (Measure.count : Measure State)
        thermodynamicBeta oneWindowEnergy =
      physicalDeltaFreeEnergy := by
  simp [Driven.deltaFreeEnergy, Gibbs.deltaFreeEnergy,
    FiniteJumpGenerator.freeEnergy_count_eq,
    finiteFreeEnergy_eq_explicit, physicalDeltaFreeEnergy]

/-- The forward law of the one-window driven specialization. -/
noncomputable def drivenForwardLaw (T : NNReal) :
    Measure (Driven.Path State 1) :=
  Driven.forwardDrivenLaw
    (Gibbs.measure (Measure.count : Measure State)
      thermodynamicBeta initialEnergy)
    oneWindowGenerator (oneWindowDuration T)

/-- The reverse law of the one-window driven specialization. -/
noncomputable def drivenReverseLaw (T : NNReal) :
    Measure (Driven.Path State 1) :=
  Driven.reverseDrivenLaw
    (Gibbs.measure (Measure.count : Measure State)
      thermodynamicBeta finalEnergy)
    oneWindowGenerator (oneWindowDuration T)

/-- Every real-valued function on the two-state counting space is integrable. -/
private theorem integrable_count_state (f : State → ℝ) :
    Integrable f (Measure.count : Measure State) := by
  exact Integrable.of_finite

/-- The general generator-driven Crooks theorem specializes to the same
asymmetric rates, endpoint work, and free-energy difference as the existing
one-window final-quench theorem. -/
theorem driven_oneWindow_crooks_physical (T : NNReal) :
    CrooksRelation (drivenForwardLaw T) (drivenReverseLaw T)
      (fun γ => ENNReal.ofReal
        (Real.exp (-thermodynamicBeta * thermodynamicStateWork γ.1)))
      (ENNReal.ofReal
        (Real.exp (-thermodynamicBeta * physicalDeltaFreeEnergy))) := by
  have h := Driven.crooks
    (Measure.count : Measure State) thermodynamicBeta
    (by norm_num [thermodynamicBeta])
    oneWindowEnergy oneWindowGenerator (oneWindowDuration T)
    (fun _ => Measurable.of_discrete)
    (fun i => integrable_count_state
      (fun x => Real.exp (-thermodynamicBeta * oneWindowEnergy i x)))
    (fun i =>
      (oneWindowGenerator i).windowBalance_of_gibbsDetailedBalance
        (oneWindowDuration T i) thermodynamicBeta
        (oneWindowEnergy i.castSucc)
        (oneWindow_isGibbsDetailedBalance i))
  simpa [drivenForwardLaw, drivenReverseLaw] using h

/-- The corresponding one-window Jarzynski equality in the existing
asymmetric-example variables. -/
theorem driven_oneWindow_jarzynski_physical (T : NNReal) :
    ∫ γ, Real.exp
          (-thermodynamicBeta * thermodynamicStateWork γ.1)
        ∂drivenForwardLaw T =
      Real.exp (-thermodynamicBeta * physicalDeltaFreeEnergy) := by
  have h := Driven.jarzynski
    (Measure.count : Measure State) thermodynamicBeta
    (by norm_num [thermodynamicBeta])
    oneWindowEnergy oneWindowGenerator (oneWindowDuration T)
    (fun _ => Measurable.of_discrete)
    (fun i => integrable_count_state
      (fun x => Real.exp (-thermodynamicBeta * oneWindowEnergy i x)))
    (fun i =>
      (oneWindowGenerator i).windowBalance_of_gibbsDetailedBalance
        (oneWindowDuration T i) thermodynamicBeta
        (oneWindowEnergy i.castSucc)
        (oneWindow_isGibbsDetailedBalance i))
  simpa [drivenForwardLaw] using h

/-- The one-window work is integrable because it depends only on the finite
terminal endpoint. -/
theorem integrable_drivenOneWindowWork (T : NNReal) :
    Integrable (fun γ : Driven.Path State 1 => thermodynamicStateWork γ.1)
      (drivenForwardLaw T) := by
  letI : IsProbabilityMeasure
      (Gibbs.measure (Measure.count : Measure State)
        thermodynamicBeta initialEnergy) :=
    Gibbs.isProbabilityMeasure_measure
      (Measure.count : Measure State) thermodynamicBeta initialEnergy
      (integrable_count_state
        (fun x => Real.exp (-thermodynamicBeta * initialEnergy x)))
  letI : IsProbabilityMeasure (drivenForwardLaw T) := by
    unfold drivenForwardLaw
    infer_instance
  apply Integrable.of_bound
    (((Measurable.of_discrete : Measurable thermodynamicStateWork).comp
      measurable_fst).aestronglyMeasurable)
    (max ‖thermodynamicStateWork State.zero‖
      ‖thermodynamicStateWork State.one‖)
  filter_upwards [] with γ
  rcases γ with ⟨s, rest⟩
  cases s
  · exact le_max_left _ _
  · exact le_max_right _ _

/-- The second law obtained from the general driven theorem specializes to the
existing asymmetric final-quench work and free-energy difference. -/
theorem driven_oneWindow_second_law (T : NNReal) :
    physicalDeltaFreeEnergy ≤
      ∫ γ, thermodynamicStateWork γ.1 ∂drivenForwardLaw T := by
  have hwork : Integrable (Driven.work oneWindowEnergy)
      (drivenForwardLaw T) := by
    exact (integrable_drivenOneWindowWork T).congr
      (ae_of_all _ fun γ =>
        (drivenWork_oneWindow_eq_thermodynamicStateWork γ).symm)
  have h := Driven.second_law
    (Measure.count : Measure State) thermodynamicBeta
    (by norm_num [thermodynamicBeta])
    oneWindowEnergy oneWindowGenerator (oneWindowDuration T)
    (fun _ => Measurable.of_discrete)
    (fun i => integrable_count_state
      (fun x => Real.exp (-thermodynamicBeta * oneWindowEnergy i x)))
    (fun i =>
      (oneWindowGenerator i).windowBalance_of_gibbsDetailedBalance
        (oneWindowDuration T i) thermodynamicBeta
        (oneWindowEnergy i.castSucc)
        (oneWindow_isGibbsDetailedBalance i))
    hwork
  simpa [drivenForwardLaw] using h

end AsymmetricExample
end TwoState
end ContinuousTimeJump
end MeasureProtocol
end CrooksJarzynski
