/-
Copyright (c) 2026 kiyo-e. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: kiyo-e
-/
import CrooksJarzynski.ContinuousTimeJumpTrajectory
import CrooksJarzynski.MeasureProtocolMarkedPhysical

/-!
# Stepwise driven continuous-time jump protocols

A driven path stores one complete fixed-horizon jump path for every protocol
window.  Consecutive windows are generated by kernels whose input is the
previous terminal state, so the constructed law carries the boundary matching
condition.  Reverse windows are sampled in reverse protocol order and their
marks are pulled back by the existing full-path reversal.
-/

open MeasureTheory ProbabilityTheory
open scoped ENNReal ProbabilityTheory

namespace CrooksJarzynski
namespace MeasureProtocol
namespace ContinuousTimeJump

universe u

namespace FullPath

variable {Ω : Type u} [MeasurableSpace Ω]

/-- Reverse a complete finite-jump path without changing its jump-count
sector. -/
def reverse : FullPath Ω → FullPath Ω
  | ⟨n, γ⟩ => ⟨n, JumpPath.reverse γ⟩

@[fun_prop]
theorem measurable_reverse :
    Measurable (reverse : FullPath Ω → FullPath Ω) := by
  intro s hs
  apply MeasurableSpace.measurableSet_iInf.mpr
  intro n
  change MeasurableSet
    ((fun γ : JumpPath Ω n => Sigma.mk n (JumpPath.reverse γ)) ⁻¹' s)
  exact ((measurable_mk n).comp JumpPath.measurable_reverse) hs

omit [MeasurableSpace Ω] in
@[simp]
theorem reverse_reverse (γ : FullPath Ω) : reverse (reverse γ) = γ := by
  rcases γ with ⟨n, γ⟩
  simp [reverse]

omit [MeasurableSpace Ω] in
@[simp]
theorem initialState_reverse (γ : FullPath Ω) :
    initialState (reverse γ) = terminalState γ := by
  rcases γ with ⟨n, γ⟩
  change γ.1 ((0 : Fin (n + 1)).rev) = γ.1 (Fin.last n)
  rw [Fin.rev_zero]

omit [MeasurableSpace Ω] in
@[simp]
theorem terminalState_reverse (γ : FullPath Ω) :
    terminalState (reverse γ) = initialState γ := by
  rcases γ with ⟨n, γ⟩
  simp [reverse, initialState, terminalState, JumpPath.reverse]

/-- Full-path reversal as a measurable equivalence. -/
noncomputable def reverseEquiv : FullPath Ω ≃ᵐ FullPath Ω where
  toEquiv :=
    { toFun := reverse
      invFun := reverse
      left_inv := fun γ => reverse_reverse γ
      right_inv := fun γ => reverse_reverse γ }
  measurable_toFun := measurable_reverse
  measurable_invFun := measurable_reverse

end FullPath

namespace FiniteJumpGenerator

variable {Ω : Type u} [Fintype Ω] [DecidableEq Ω]
variable [MeasurableSpace Ω] [MeasurableSingletonClass Ω]

/-- One forward protocol window.  The mark is the complete fixed-horizon path
actually sampled from `pathLawFrom`; its first output component is the recorded
terminal state. -/
noncomputable def forwardWindowKernel
    (G : FiniteJumpGenerator Ω) (T : NNReal) :
    ProbabilityTheory.Kernel Ω (Ω × FullPath Ω) where
  toFun x :=
    (G.pathLawFrom T x).map
      (fun γ => (FullPath.terminalState γ, γ))
  measurable' := Measurable.of_discrete

@[simp]
theorem forwardWindowKernel_apply
    (G : FiniteJumpGenerator Ω) (T : NNReal) (x : Ω) :
    G.forwardWindowKernel T x =
      (G.pathLawFrom T x).map
        (fun γ => (FullPath.terminalState γ, γ)) :=
  rfl

noncomputable instance instIsMarkovKernelForwardWindowKernel
    (G : FiniteJumpGenerator Ω) (T : NNReal) :
    IsMarkovKernel (G.forwardWindowKernel T) := by
  constructor
  intro x
  change IsProbabilityMeasure
    ((G.pathLawFrom T x).map
      (fun γ => (FullPath.terminalState γ, γ)))
  exact Measure.isProbabilityMeasure_map
    (FullPath.measurable_terminalState.prodMk measurable_id).aemeasurable

/-- One reverse-experiment window in forward-aligned coordinates.  The reverse
experiment starts at the later endpoint, and its complete path mark is reversed
before it is stored. -/
noncomputable def reverseWindowKernel
    (G : FiniteJumpGenerator Ω) (T : NNReal) :
    ProbabilityTheory.Kernel Ω (Ω × FullPath Ω) where
  toFun y :=
    (G.pathLawFrom T y).map
      (fun γ => (FullPath.terminalState γ, FullPath.reverse γ))
  measurable' := Measurable.of_discrete

@[simp]
theorem reverseWindowKernel_apply
    (G : FiniteJumpGenerator Ω) (T : NNReal) (y : Ω) :
    G.reverseWindowKernel T y =
      (G.pathLawFrom T y).map
        (fun γ => (FullPath.terminalState γ, FullPath.reverse γ)) :=
  rfl

noncomputable instance instIsMarkovKernelReverseWindowKernel
    (G : FiniteJumpGenerator Ω) (T : NNReal) :
    IsMarkovKernel (G.reverseWindowKernel T) := by
  constructor
  intro y
  change IsProbabilityMeasure
    ((G.pathLawFrom T y).map
      (fun γ => (FullPath.terminalState γ, FullPath.reverse γ)))
  exact Measure.isProbabilityMeasure_map
    (FullPath.measurable_terminalState.prodMk
      FullPath.measurable_reverse).aemeasurable

/-- Measure-level detailed balance for one complete path window. -/
def WindowBalance
    (equilibrium : Measure Ω)
    (G : FiniteJumpGenerator Ω) (T : NNReal) : Prop :=
  equilibrium ⊗ₘ G.forwardWindowKernel T =
    (equilibrium ⊗ₘ G.reverseWindowKernel T).map
      (Marked.swapEndpointsEquiv (Ω := Ω) (Λ := FullPath Ω))

end FiniteJumpGenerator

namespace Driven

variable {Ω : Type u} [Fintype Ω] [DecidableEq Ω]
variable [MeasurableSpace Ω] [MeasurableSingletonClass Ω]

/-- The reverse-oriented carrier for `M` consecutive jump-process windows. -/
abbrev Path (Ω : Type u) [MeasurableSpace Ω] (M : ℕ) :=
  Marked.MarkedPath Ω (FullPath Ω) M

/-- Forward law obtained by binding the fixed-initial path law of every window
at the terminal state of the preceding window. -/
noncomputable def forwardDrivenLaw
    {M : ℕ} (initial : Measure Ω)
    (generator : Fin M → FiniteJumpGenerator Ω)
    (duration : Fin M → NNReal) : Measure (Path Ω M) :=
  Marked.reversedForwardPathMeasure initial
    (fun i => (generator i).forwardWindowKernel (duration i))

noncomputable instance instIsProbabilityMeasureForwardDrivenLaw
    {M : ℕ} (initial : Measure Ω)
    (generator : Fin M → FiniteJumpGenerator Ω)
    (duration : Fin M → NNReal)
    [IsProbabilityMeasure initial] :
    IsProbabilityMeasure (forwardDrivenLaw initial generator duration) := by
  unfold forwardDrivenLaw
  infer_instance

/-- Reverse law: the recursive reverse path measure starts from the final Gibbs
state, visits the windows in reverse order, and reverses every stored window
path. -/
noncomputable def reverseDrivenLaw
    {M : ℕ} (final : Measure Ω)
    (generator : Fin M → FiniteJumpGenerator Ω)
    (duration : Fin M → NNReal) : Measure (Path Ω M) :=
  Marked.reversePathMeasure final
    (fun i => (generator i).reverseWindowKernel (duration i))

noncomputable instance instIsProbabilityMeasureReverseDrivenLaw
    {M : ℕ} (final : Measure Ω)
    (generator : Fin M → FiniteJumpGenerator Ω)
    (duration : Fin M → NNReal)
    [IsProbabilityMeasure final] :
    IsProbabilityMeasure (reverseDrivenLaw final generator duration) := by
  unfold reverseDrivenLaw
  infer_instance

/-- Work performed by the instantaneous energy switches at all window
endpoints. -/
noncomputable def work
    {M : ℕ} (energy : Fin (M + 1) → Ω → ℝ) : Path Ω M → ℝ :=
  Marked.endpointPathWork energy

/-- The endpoint Gibbs free-energy difference. -/
noncomputable def deltaFreeEnergy
    {M : ℕ} (base : Measure Ω) (β : ℝ)
    (energy : Fin (M + 1) → Ω → ℝ) : ℝ :=
  Gibbs.deltaFreeEnergy base β energy

omit [Fintype Ω] [DecidableEq Ω] [MeasurableSingletonClass Ω] in
/-- The driven work observable is measurable. -/
theorem measurable_work
    {M : ℕ} (energy : Fin (M + 1) → Ω → ℝ)
    (henergy : ∀ i, Measurable (energy i)) :
    Measurable (work energy) :=
  Marked.measurable_endpointPathWork energy henergy

/-- **Crooks relation for the constructed stepwise driven path laws.** -/
theorem crooks
    {M : ℕ} (base : Measure Ω) [NeZero base]
    (β : ℝ) (hβ : β ≠ 0)
    (energy : Fin (M + 1) → Ω → ℝ)
    (generator : Fin M → FiniteJumpGenerator Ω)
    (duration : Fin M → NNReal)
    (henergyMeas : ∀ i, Measurable (energy i))
    (henergyInt : ∀ i,
      Integrable (fun x => Real.exp (-β * energy i x)) base)
    (hbalance : ∀ i,
      (generator i).WindowBalance
        (Gibbs.measure base β (energy i.castSucc)) (duration i)) :
    CrooksRelation
      (forwardDrivenLaw
        (Gibbs.measure base β (energy 0)) generator duration)
      (reverseDrivenLaw
        (Gibbs.measure base β (energy (Fin.last M))) generator duration)
      (fun γ => ENNReal.ofReal (Real.exp (-β * work energy γ)))
      (ENNReal.ofReal
        (Real.exp (-β * deltaFreeEnergy base β energy))) := by
  simpa [forwardDrivenLaw, reverseDrivenLaw, work, deltaFreeEnergy,
    FiniteJumpGenerator.WindowBalance] using
    (Marked.multiStep_endpoint_crooks_physical
      (Λ := FullPath Ω) base β hβ energy
      (fun i => (generator i).forwardWindowKernel (duration i))
      (fun i => (generator i).reverseWindowKernel (duration i))
      henergyMeas henergyInt hbalance)

/-- **Jarzynski equality for the constructed stepwise driven forward law.** -/
theorem jarzynski
    {M : ℕ} (base : Measure Ω) [NeZero base]
    (β : ℝ) (hβ : β ≠ 0)
    (energy : Fin (M + 1) → Ω → ℝ)
    (generator : Fin M → FiniteJumpGenerator Ω)
    (duration : Fin M → NNReal)
    (henergyMeas : ∀ i, Measurable (energy i))
    (henergyInt : ∀ i,
      Integrable (fun x => Real.exp (-β * energy i x)) base)
    (hbalance : ∀ i,
      (generator i).WindowBalance
        (Gibbs.measure base β (energy i.castSucc)) (duration i)) :
    ∫ γ, Real.exp (-β * work energy γ)
        ∂forwardDrivenLaw
          (Gibbs.measure base β (energy 0)) generator duration =
      Real.exp (-β * deltaFreeEnergy base β energy) := by
  simpa [forwardDrivenLaw, work, deltaFreeEnergy,
    FiniteJumpGenerator.WindowBalance] using
    (Marked.multiStep_endpoint_jarzynski_integral
      (Λ := FullPath Ω) base β hβ energy
      (fun i => (generator i).forwardWindowKernel (duration i))
      (fun i => (generator i).reverseWindowKernel (duration i))
      henergyMeas henergyInt hbalance)

/-- **Average-work second law for the constructed stepwise driven law.** -/
theorem second_law
    {M : ℕ} (base : Measure Ω) [NeZero base]
    (β : ℝ) (hβ : 0 < β)
    (energy : Fin (M + 1) → Ω → ℝ)
    (generator : Fin M → FiniteJumpGenerator Ω)
    (duration : Fin M → NNReal)
    (henergyMeas : ∀ i, Measurable (energy i))
    (henergyInt : ∀ i,
      Integrable (fun x => Real.exp (-β * energy i x)) base)
    (hbalance : ∀ i,
      (generator i).WindowBalance
        (Gibbs.measure base β (energy i.castSucc)) (duration i))
    (hworkInt : Integrable (work energy)
      (forwardDrivenLaw
        (Gibbs.measure base β (energy 0)) generator duration)) :
    deltaFreeEnergy base β energy ≤
      ∫ γ, work energy γ
        ∂forwardDrivenLaw
          (Gibbs.measure base β (energy 0)) generator duration := by
  simpa [forwardDrivenLaw, reverseDrivenLaw, work, deltaFreeEnergy,
    FiniteJumpGenerator.WindowBalance] using
    (Marked.multiStep_endpoint_second_law
      (Λ := FullPath Ω) base β hβ energy
      (fun i => (generator i).forwardWindowKernel (duration i))
      (fun i => (generator i).reverseWindowKernel (duration i))
      henergyMeas henergyInt hbalance hworkInt)

omit [Fintype Ω] [DecidableEq Ω] [MeasurableSingletonClass Ω] in
/-- For one window, driven work is exactly the terminal energy quench. -/
theorem work_one
    (energy : Fin 2 → Ω → ℝ) (γ : Path Ω 1) :
    work energy γ = energy 1 γ.1 - energy 0 γ.1 :=
  Marked.endpointPathWork_one energy γ

end Driven
end ContinuousTimeJump
end MeasureProtocol
end CrooksJarzynski
